 
contador = 1 # CREAMOS UNA VARIABLE LLAMADA CONTADOR Y LA INICIAMOS EN 1 

almacenamiento = "hola" # CREAMOS OTRA VARIABLE LLAMADA ALMACENAMIENTO PARA PODER GUARDAR NUESTRA CONTRASENA PARA EL LOGIN DE VERIFICACION 

while contador<= 3: # USAMOS UN CICLO WHILE PARA QUE PIDA LA CONTRASENA 3 VECES POR ESO LA CONDICION DE <=3

  print("DIGITE SU CONTRASENA PORFAVOR") # LE PEDIMOS AL USUARIO QUE DIGITE SU CONTRASENA PARA PODER INICIAR SESION EN SU LOGIN
  contrasena = input() # CREAMOS UNA VARIABLE PARA ALMACENAR LA CONTRASENA


  contador = contador + 1 # AUMENTAMOS EL CONTADOR PARA QUE PUEDA AUMENTAR HASTA LLEGAR A LA CONDICION DEL CICLO WHILE 
  if contrasena == almacenamiento:
    print("SU CONTRASENA ES CORRECTA")
    contador = 5
  else:
    print("SU CONTRASENA ES INCORRECTA")
  if contador == 4: # HACEMOS LA COMPARACION DE CONTADOR = 4 SI LOS INTENTOS SON MAS DE 3 OSEA 4 TIENE QUE CAMBIAR LA CONTRASENA
    print("PORFAVOR CAMBIA TU CONTRASENA YA HAS TENIDO 3 INTENTOS")
    
 

